### PR TITLE
make fs operations optimistic

### PR DESCRIPTION
**Pull request by suchipi**
This changes the fs functions to try the normal impl first before calling pkglock.resolve.

It looks like you went ahead and did some of these already over the last few days- I didn't know you wanted them done sooner than the weekend or I wouldn't have volunteered to do them, sorry to keep you waiting.

The merge conflicts may not have been resolved properly because of that; I've checked **Allow edits from maintainers** so please do whatever you feel makes the most sense.

### CODE REVIEW

**Review by zkat — APPROVED** [review]
nice! You even fixed some bugs in the hacky versions I did while debugging a different thing! Sorry for all the conflicts. I was trying to get another thing working, and you may have fixed it lol

**Comment by zkat** [comment]
YOU DID FIX IT. THANK YOU!

#nailedit

**Comment by suchipi** [comment]
I hope I didn't do too much damage 😉

**Comment by suchipi** [comment]
oh nice!

**Comment by zkat** [comment]
omg this fixed one thing while breaking another. For some reason, I've started getting EEXIST errors when trying to initial-load a dep (from an empty cache). I don't know which of the changes is causing this but I guess I'll have to comb through them one-by-one. Really about time we have unit tests for this. sigh.

**Comment by zkat** [comment]
I managed to fix a few other bits too, at least.

**Comment by suchipi** [comment]
sorry about that. I wasn't sure how to test it

**Comment by zkat** [comment]
I found the bugs! Everything is good now. I'll stub out some tests soon so folks can help with testing this 👍

**Comment by tchalvak** [comment]
+1 for unit tests

**Pull request merged**
