### PR TITLE
 fix(lint): downgrade `standard` version to avoid jsx parse errors

### PR DESCRIPTION
**Pull request by alopezsanchez**
Please, review the changes. The tests are green.

### CODE REVIEW

**Comment by zkat** [comment]
Seriously? It was the upgrade?!

**Comment by zkat** [comment]
Cc @feross

**Review by zkat — APPROVED** [review]

**Comment by zkat** [comment]
I've re-done this manually for the latest code and credited the commit to you, so consider it merged. Thank you!

**Comment by feross** [comment]
Sorry for the delay. Just seeing this now. The correct way to tell `standard` that you're using jsx is with a comment like `/** @jsx h */` somewhere in the file.

You can see an example in this file: https://github.com/feross/bitmidi.com/blob/f780d0a1a4a958249cd8853d96f159ad17239ed9/src/views/link.mjs#L1

**Pull request closed without merging**
