### PR TITLE
Consider how "crux" is perceived across cultures 

### PR DESCRIPTION
**Pull request by jakeNiemiec**
Just 2 quick points, this is not to convince anyone, just to inform. Feel free to close and disregard if you don't see this as a problem.

### 1. Etymology of crux: torture by hanging or "one who deserves to be hanged"

You wouldn't name something `crux` for the same reason you wouldn't name something `lynch`: the connotations are overwhelmingly negative for most (if not all) languages with latin roots. Both are also reminiscent of ugly, terrible parts of history.

Even in common parlance, it is associated with difficulty. Compare this against a name that sounds like it is easy to use or inspires confidence. 

Again, the association of `crux` with torture, hanging and impalement would be far stronger in Europe than the US.

https://en.wiktionary.org/wiki/crux#Noun_3
https://www.etymonline.com/word/crux
https://www.merriam-webster.com/dictionary/crux

### 2. "crux" is closely associated with Catholicism, esp. where latin is ceremoniously used
Nothing wrong with this, but not ideal for the name of a buildtool that will be googled. Again, the connotations will be stronger in Europe, in languages that are close to their latin roots.

There are also several publications, places and groups that take advantage and incorporate this. eg:

https://cruxnow.com/
https://archives.cjr.org/behind_the_news/_the_boston_globe_launches_cru.php
http://www.cruxbooks.com/

As we saw with that [ErLang package manager](https://groups.google.com/forum/#!topic/erlang-programming/mADyk39WgfI%5B1-25%5D), naming things is hard in a global, connected world; I hope this comes across as helpful and not "concern trolling". Best of luck on this project!

[Edited by @zkat to remove a graphic inline image]

### CODE REVIEW

**Comment by iarna** [comment]
1. Wow I had no idea, yeah, no, those are all good reasons to change it.
2. This was already not a name we were planning to keep long term, its more of a code name, so changing it is cheap.
3. I would love a new and better name!

I'd love some help brainstorming new names, @zkat recommends `tink` would I'm liking a lot…

**Comment by ioncorimenia** [comment]
A simple acronym could work as well. Like NID - Node Instant Dependencies or NOD - Node On-demand Dependencies.

**Comment by jakeNiemiec** [comment]
<sub>(sorry about the image)</sub>
> zkat recommends `tink` which I'm liking a lot…

I think `tink` is a good idea. It fits better with lighthearted feel of the JS ecosystem. 

>@iarna I'd love some help brainstorming new names

I was going to make recommendations, but I honestly couldn't think of anything meaningfully better. You could see if npm.community has any good ideas.

Simply being able to "point" to dependencies online is an exciting development.
 My one initial thought was since `package-map` is being introduced you could play on **cartography/map/courier themes** (npm/cartogram? carto?).

**Comment by iarna** [comment]
I've renamed to tink. Thanks all! =)

(There will be more opportunities to bikeshed names but I think we can stay with tink for a bit.)

**Comment by MiracleBlue** [comment]
I like Tink.  It's a fun name!

**Comment by ghost** [comment]
Tink is the name of popular [personal finance app](https://consumer.tink.se/) and [financial API](https://business.tink.se/) in Europe.

https://www.crunchbase.com/organization/tink

**Comment by DanielRuf** [comment]
And it is already registered as package name. Much confusion in teams here.

**Pull request closed without merging**
