### PR TITLE
test: command run basic test

### PR DESCRIPTION
**Pull request by maddhruv**
- deleted not completed `pkgLock` test
- travis build might pass

### CODE REVIEW

**Comment by zkat** [comment]
I'd rather you fill in `pkglock.test` instead of delete it altogether. It needs to be tested.

**Comment by maddhruv** [comment]
> I'd rather you fill in pkglock.test instead of delete it altogether.

I was trying to figure out the Travis build failure as the pkgLock tests were not complete and log pending
would add the tests back again when writing the tests :handshake: 

until then I think this can be merged

**Comment by zkat** [comment]
I'm not going to merge it -- pending tests do not trigger failures.

**Comment by maddhruv** [comment]
restored the pkglock test file

**Comment by maddhruv** [comment]
@zkat i have restored the `pkglock` test file

**Comment by zkat** [comment]
This is a great idea! But shelljs is seriously not required here. Please use a regular `child_process` call for this unless there's something really compelling about shjs.

**Review by zkat — CHANGES_REQUESTED** [review]
no shelljs please

**Comment by maddhruv** [comment]
> But shelljs is seriously not required here. Please use a regular child_process

okay, will update

**Pull request closed without merging**
