### PR TITLE
test: add more simple baseline tests for fs.js

### PR DESCRIPTION
**Pull request by jchip**
- add more baseline tests for fs.js

- note that the `chmod` test fails but without the `overrideNode` it actually passes.

### CODE REVIEW

**Comment by zkat** [comment]
ooh. That must mean there's a bug with `chmod`, then, yeah? You wanna try fixing the bug as part of this PR or would you rather I wait until it gets fixed elsewhere to merge this?

**Comment by jchip** [comment]
I didn't fix it because I saw there's another fs.js refactor task someone else's working on.

I could fix it if it doesn't conflict with that.

**Comment by jchip** [comment]
actually, I think I don't know enough about the code to fix it yet. :)

The problem is here https://github.com/npm/tink/blob/latest/lib/node/fs.js#L438

I think it should be `return cb(err)` there.

Also, looking at the various exist `cb(err)`, I think `cb` could get called multiple times unless each `cb(err)` is `return cb(err)`

**Comment by zkat** [comment]
You're right! All of those cb calls need to have `return`. Can you adda new PR with that? I'll merge this in the meantime

**Pull request merged**
