### PR TITLE
docs(profile): add `profile` documentation to README

### PR DESCRIPTION
**Pull request by alopezsanchez**

### CODE REVIEW

**Comment by zkat** [comment]
@alopezsanchez Could you redo this PR on the latest branch? It seems to have picked up a bunch of unrelated changes. It otherwise LGTM.

**Review by zkat — CHANGES_REQUESTED** [review]
Lots of unrelated changes in the PR for some reason.

**Comment by alopezsanchez** [comment]
Yes! I close this.

**Comment by alopezsanchez** [comment]
@zkat new PR: https://github.com/npm/tink/pull/44

**Pull request closed without merging**
